services:
    sensuy:
        build:
            context: .
            dockerfile: Dockerfile
            target: production  # Matches the stage name in your Dockerfile
        container_name: sensuy-app
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www:delegated  # For development hot-reloading [[9]]
        environment:
            APP_NAME: Sensuy
            APP_ENV: production
            # Add other environment variables here if needed
        healthcheck:
            test: ["CMD", "curl", "--fail", "http://localhost:8000/up"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 5s
        networks:
            - sensuy-network

networks:
    sensuy-network:
        driver: bridge
