name: "sensuy"

services:
    sensuy:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "127.0.0.1:8001:8000"
        volumes:
            - sensuy:/var/www/storage
        networks:
            - db-network

    meilisearch:
        image: getmeili/meilisearch:latest
        ports:
            - "127.0.0.1:7700:7700"
        environment:
            MEILI_MASTER_KEY: "masterKey"
        volumes:
            - meili_data:/data.ms
        restart: unless-stopped

volumes:
    sensuy:
    meili_data:

networks:
    db-network:
        driver: bridge
